### ISSUE TITLE
This plugin does not handling AppNotFoundException

### ISSUE THREAD

**Issue by subair-zufi** [GJJ2019/easy_upi_payment#5]
When no upi app is installed, the app got crashed.

Error report:
```
E/AndroidRuntime(24000): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sirajulhuda.app/dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity}: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app exists on this device to perform this transaction.
E/AndroidRuntime(24000): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
E/AndroidRuntime(24000): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
E/AndroidRuntime(24000): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(24000): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(24000): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(24000): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
E/AndroidRuntime(24000): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24000): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(24000): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(24000): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
E/AndroidRuntime(24000): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24000): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(24000): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime(24000): Caused by: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app exists on this device to perform this transaction.
E/AndroidRuntime(24000): 	at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.throwOnAppNotFound$EasyUpiPayment_release(PaymentUiActivity.kt:128)
E/AndroidRuntime(24000): 	at dev.shreyaspatil.easyupipayment.ui.PaymentUiActivity.onCreate(PaymentUiActivity.kt:62)
E/AndroidRuntime(24000): 	at android.app.Activity.performCreate(Activity.java:8290)
E/AndroidRuntime(24000): 	at android.app.Activity.performCreate(Activity.java:8270)
E/AndroidRuntime(24000): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/AndroidRuntime(24000): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
E/AndroidRuntime(24000): 	... 12 more
```

**Comment by GJJ2019** [comment]
I cant do much in this I'll try to implementing something to catch this 
https://github.com/PatilShreyas/EasyUpiPayment-Android/issues/157

**Comment by Rohitbagul003** [comment]
Am also facing this issue
